config/routes.rb
Rails.application.routes.draw do

    get 'posts/search', to: 'posts#search'

    post 'support/request_support'

    resources :posts do
        collection do
            get "by_tag/:tag", to: "posts#by_tag", as: "tagged"
        end
    end

    resources :idea_posts do
        collection do
          get "by_tag/:tag", to: "idea_posts#by_tag", as: "tagged"
        end
    end

    resources :comments, only: [:create]

    namespace :api do
        namespace :v1 do
          resources :comments
          resources :posts

          devise_scope :user do
            post "sign_up", to: "registrations#create"
            post "sign_in", to: "sessions#create"
            post "sign_out", to: "sessions#destroy"
          end
        end
    end


    resources :posts, param: :slug do
        resource :favorite, only: [:create, :destroy]
    end

    devise_for :users

    get 'welcome/support'
    root "pages#trends"

    get 'search', to: 'pages#search'
    get 'stones', to: 'pages#stones'

    get 'history', to: 'pages#history'
    get 'jewelrystory', to: 'pages#jewelrystory'

    get 'cartier', to: 'pages#cartier'
    get 'trends', to: 'pages#trends'
    get 'zircon', to: 'pages#zircon'


    get 'lk', to: 'pages#lk'

     post 'support/request_support'

   resources :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :body, presence: true

    has_many :replies, class_name: "Comment", foreign_key: "reply_to_comment_id", dependent: :destroy
    belongs_to :comment, class_name: "Comment", foreign_key: "reply_to_comment_id", optional: true

    belongs_to :post
    belongs_to :user

    default_scope { where(reply_to_comment_id: nil) }

    # scope :out_of_print, -> { where(out_of_print: true) }

        # def api_as_json
    #     {
    #         body: body
    #     }
    # end

end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApplicationController

  # load_and_authorize_resource
  # before_action :set_comment, only: %i[ show edit update destroy ]

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @user = User.find_by_jti(decrypt_payload[0]['jti'])
    @comment = @user.comments.new(comment_params)

    ActionCable.server.broadcast("notifications_#{@post.user.id}", { text: "New comment for your post", type: "Post", id: @post.id })

    if @comment.save
      render json: @comment.as_json
    else
      render json: @comment.errors, status: :unprocessable_entity
    end

  end

  private
    def comment_params
      params.require(:comment).permit(:body, :post_id)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_back fallback_location: root_path, notice: "Комментарий успешно создан" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :post_type, :post_id).merge(user_id: current_user.id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
 <div class="cooment1">
      <div class="slot">
          <img class="avatar" src="/assets/comment/avatar1.jpg" alt="Avatar">
          <div class="account-info">
              <span class="account-name"><%= post.user.email.split("@")[0] %></span>
              <span class="time-ago">2 часа</span>
          </div>
      </div>
      <div class="comment-content">
          <p class="comment-text"><%= comment.body %></p>
          <div class="interactions">
              <img class="like-icon" src="/assets/comment/like.svg" alt="Like">
              <span class="like-count">8</span>
              <span class="reply">Ответить</span>
          </div>
      </div>

            <%#= link_to "", edit_comment_path(comment), class:"PostCommentIcon Edit" %>
            <%#= link_to "", comment, method: :delete, class:"PostCommentIcon Trash" %>
 </div>

app/views/comments/_form.html.erb
<%= form_with(model: Comment.new, class: "comment-form") do |form| %>
  <div>
    <%= form.hidden_field :post_type, value: post.class %>
    <%= form.hidden_field :post_id, value: post.id %>
  </div>
  <% if can? :create, comment %>
      <%= form.text_area :body, placeholder: "Написать комментарии..", class: "A_CreateCommentInput" %>
      <%= form.submit :"Отправить", class: "submit-btn" %>
  <% end %>
<% end %>