config/routes.rb
Rails.application.routes.draw do

    get 'posts/search', to: 'posts#search'

    post 'support/request_support'

    resources :posts do
        collection do
            get "by_tag/:tag", to: "posts#by_tag", as: "tagged"
        end
    end

    resources :idea_posts do
        collection do
          get "by_tag/:tag", to: "idea_posts#by_tag", as: "tagged"
        end
    end

    resources :comments, only: [:create]

    namespace :api do
        namespace :v1 do
          resources :comments
          resources :posts

          devise_scope :user do
            post "sign_up", to: "registrations#create"
            post "sign_in", to: "sessions#create"
            post "sign_out", to: "sessions#destroy"
          end
        end
    end


    resources :posts, param: :slug do
        resource :favorite, only: [:create, :destroy]
    end

    devise_for :users

    get 'welcome/support'
    root "pages#trends"

    get 'search', to: 'pages#search'
    get 'stones', to: 'pages#stones'

    get 'history', to: 'pages#history'
    get 'jewelrystory', to: 'pages#jewelrystory'

    get 'cartier', to: 'pages#cartier'
    get 'trends', to: 'pages#trends'
    get 'zircon', to: 'pages#zircon'


    get 'lk', to: 'pages#lk'

     post 'support/request_support'

   resources :users
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # Meta
    @title = "Шкатулка"
    # end

    @recom_post1 = Post.find_by(id: "1")

    # ActionCable.server.broadcast("notifications_channel", { body: "LOOCHOK" })
  end

  def search
    @items = PgSearch.multisearch(params['search'])
  end
end

app/views/welcome/_support_form.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "enter", "tech" %>
<% end %>
<section class="main-section">
<div class="background">
    <%= form_with(model: support, url: support_request_support_path) do |form| %>
      <% if support.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(support.errors.count, "error") %>. Обращение не было отправлено:</h2>

          <ul>
            <% support.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
<div class="banner">
      <div class="enter">
        <h1 class="title__enter">Поддержка</h1>
        <div class="wrapper__denter">
                    <%= form.email_field :email, class: "mail", placeholder: "Ваша почта" %>

                    <%= form.text_area :body, class: "mail", placeholder: "Расскажите, что случилось" %>

                    <%= form.submit :"Отправить", class: "enter_btn btn__text" %>
        </div>
      </div>
</div>

    <% end %>
</div>
</section>

app/views/welcome/support.html.erb
<dev class="S_SupportPage">
    <%= render "support_form", support: Support.new %>
</dev>