config/routes.rb
Rails.application.routes.draw do

    get 'posts/search', to: 'posts#search'

    post 'support/request_support'

    resources :posts do
        collection do
            get "by_tag/:tag", to: "posts#by_tag", as: "tagged"
        end
    end

    resources :idea_posts do
        collection do
          get "by_tag/:tag", to: "idea_posts#by_tag", as: "tagged"
        end
    end

    resources :comments, only: [:create]

    namespace :api do
        namespace :v1 do
          resources :comments
          resources :posts

          devise_scope :user do
            post "sign_up", to: "registrations#create"
            post "sign_in", to: "sessions#create"
            post "sign_out", to: "sessions#destroy"
          end
        end
    end


    resources :posts, param: :slug do
        resource :favorite, only: [:create, :destroy]
    end

    devise_for :users

    get 'welcome/support'
    root "pages#trends"

    get 'search', to: 'pages#search'
    get 'stones', to: 'pages#stones'

    get 'history', to: 'pages#history'
    get 'jewelrystory', to: 'pages#jewelrystory'

    get 'cartier', to: 'pages#cartier'
    get 'trends', to: 'pages#trends'
    get 'zircon', to: 'pages#zircon'


    get 'lk', to: 'pages#lk'

     post 'support/request_support'

   resources :users
end

app/models/post.rb
class Post < ApplicationRecord
    include PgSearch::Model
    multisearchable against: [:title, :description]

    extend FriendlyId
    friendly_id :title, use: :slugged

    validates :title, presence: true
    validates :type, presence: true
    validates :post_image, presence: true

    has_many :comments, dependent: :destroy
    belongs_to :user
    mount_uploader :post_image, PostImageUploader

        has_many :favorites
        has_many :favorited_by, through: :favorites, source: :user

    acts_as_taggable_on :tags

    # def api_as_json
    #     {
    #         title: title,
    #         description: description,
    #         post_image: post_image
    #     }
    # end

    # def to_param
    #     "#{title.parameterize}"
    # end

end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController

  def index 
    @posts = Post.all

    # render :index
    # render json: @posts

    # render json: @posts.map { |post| post.api_as_json }
  end

  def show
    # @post = Post.find(params[:id])
    @post = Post.friendly.find(params[:id]) 
    # - что с френдли айди на этом этапе?
  end

  def create
    @user = User.find_by_jti(decrypt_payload[0]['jti'])
    @post = @user.posts.new(sti_post_params)

    if @post.save
      render json: @post.as_json
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # def update
  #   if @post.update(sti_post_params)
  #     format.json { render :show, status: :ok, location: @post }
  #   else
  #     format.json { render json: @post.errors, status: :unprocessable_entity }
  #   end
  # end

  # def destroy
  #   @post.destroy
  #   format.json { head :no_content }
  # end

  private
    def sti_post_params
        p = nil
        
      if params[:post]
        p = params.require(:post)
      elsif params[:idea_post]
        p = params.require(:idea_post)
      elsif params[:tutorial_post]
        p = params.require(:tutorial_post)
      end

      p.permit(:title, :type, :description, :post_image, :contetn_link, :tag_list, :created_at)
    end

end

app/controllers/posts_controller.rb
# переделать потом

class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post, only: %i[ show edit update destroy ]

   def search
       query = params[:query]
       results = PgSearch.multisearch(query)
       render json: results.map { |result| result.searchable }
   end

  def show
    @title = "Шкатулка | #{@post.title}"
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(sti_post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Пост успешно создан" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(sti_post_params)
        format.html { redirect_to post_url(@post), notice: "Пост успешно изменён" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Пост успешно удалён" }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :description, :content_link, :type)
    end

    def sti_post_params
        p = nil
        
      if params[:post]
        p = params.require(:post)
      elsif params[:idea_post]
        p = params.require(:idea_post)
      elsif params[:tutorial_post]
        p = params.require(:tutorial_post)
      end

      p.permit(:title, :type, :description, :post_image, :contetn_link, :tag_list, :created_at).merge(user_id: current_user.id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<h2 style="font-size:32px; font-weight:900;"><%= post.class %></h2>

<%= form_with(model: post, url: url) do |form| %>
  <%#= form_with(model: post, url: posts_path) do |form| %>
    <% if post.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(post.errors.count, "error") %>. Пост не может быть сохранён:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :"Заголовок", style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :"Текст публикации", style: "display: block" %>
      <%= form.text_area :description %>
    </div>

    <div>
      <%= form.label :"Добавить ссылку", style: "display: block" %>
      <%= form.text_field :content_link %>
    </div>

    <div>
      <%= form.label :"Загрузить изображение", style: "display: block" %>
      <%= form.file_field :post_image%>
    </div>

    <div>
      <%= form.label :"Тип" %>
      <%= form.select :type, ["IdeaPost", "TutorialPost"]%>
    </div>

    <div>
      <%= form.submit :"Опубликовать"%>
    </div>
  <% end %>

app/views/posts/_postideapage.html.erb
 <div class="main__navigation">
  <a href="/jewelrystory" class="bttn">
                 <img src="/assets/jewelry/btn.svg" alt="">
             </a>
            <p class="author grey__text">Автор
                статьи:<br> <%= post.user.email %></p>
        </div>


		<div class="background">
            <div class="banner">
                <div class="banner__img">
                    <%= image_tag post.post_image.url %>
                    <!--img src="/assets/zircon/bannerzircon.jpg"-->
                </div>
                <div class="jewelry">
                    <div class="title__name">
                        <p class="tab grey__text"><%= post.title%></p>
                        <h1 class="jewelry_title"><%= post.title.split('/').last %></h1>
                        <div class="icon">
                            <img class="icon__img" src="/assets/jewelry/watch.svg" alt="">
                            <p class="icon__text grey__text">1237</p>
                            <img class="icon__img" src="/assets/jewelry/like.svg" alt="">
                            <p class="icon__text grey__text">543</p>
                        </div>
                    </div>
                    <div class="line">
                        <p class="data__text grey__text"><%= post.created_at.strftime("%d.%m.%Y") %></p>
                    </div>
                    <p class="jewelry__text">
                        <%= post.description.html_safe %>
                    </p>
                    <div class="zircon__row">
                        <div class="img__js">
                            <img class="zircon__first" src="/assets/zircon/zirkon.jpg" alt="">
                            <div class="zir" href="#zircon__second">
                                <button class="icons__img">
                                    <img class="" src="/assets/zircon/icon.svg" alt="">
                                </button>
                            </div>
                        </div>
                        <div class="img__js hidden">
                            <img class="zircon__second " src="/assets/zircon/2.jpg" alt="">
                            <div class="zir" href="#zircon__second">
                                <button class="icons__img ">
                                    <img class="" src="/assets/zircon/icon.svg" alt="">
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popular">
                    <div class="wrapper">
                        <div class="title-group">
                            <h1 class="jewelry_title">Читать еще:</h1>
                            <div class="divider__second">
                                <div class="highlight__second"></div>
                            </div>
                        </div>
                        <div class="popular rec__visible">
                            <div class="popular__flex rec__flex">
                                <a class="popular__item rec__item">
                                    <div class="backgradient">
                                        <img class="popular__img rec__img" src="/assets/stones/topaz.png" alt="">
                                    </div>
                                    <p class="popular__text rec__text text">Топаз</p>
                                    <button class="popular__btn rec__btn">#Камни</button>
                                </a>
                                <a class="popular__item rec__item">
                                    <div class="backgradient">
                                        <img class="popular__img rec__img" src="/assets/stones/opal.png" alt="">
                                    </div>
                                    <p class="popular__text rec__text text">Опал</p>
                                    <button class="popular__btn rec__btn">#Камни</button>
                                </a>
                                <a class="popular__item rec__item">
                                    <div class="backgradient">
                                        <img class="popular__img rec__img" src="/assets/stones/alexandrit.png" alt="">
                                    </div>
                                    <p class="popular__text rec__text text">Александрит</p>
                                    <button class="popular__btn rec__btn">#Камни</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

app/views/posts/edit.html.erb
<div class="contentPage">

  <h1>Редактирование поста</h1>

  <%= render "form", post: @post, url: post_path(@post) %>

  <div>
    <%= link_to "Показать пост", post_path(@post) %> |
    <%= link_to "Обратно ко всем постам", posts_path %>
  </div>

</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="contentPage">

  <h1>Посты</h1>

  <div class="tagChipsRow">
    <% Post.tag_counts_on(:tags).each do |tag| %>
      <%= link_to tagged_posts_path(tag.name) do %>
        <div class="tagChips">
          <%= tag.name %>
        </div>
      <% end %>
    <% end %>
  </div>

  <% if can? :create, Post %>
    <%= link_to "Новый пост", new_post_path %>
  <% end %>

  <div id="posts">
    <%#= render @posts %>
  </div>

  <div id="posts">
    <% @posts.each do |post| %>
      <%= link_to post_path(post) do %>
        <%= render post %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/posts/new.html.erb
<div class="contentPage">

  <h1>Новый пост</h1>

  <%= render "form", post: @post, url: posts_path %>

  <%#= render "form", post: @post %>

  <div>
    <%= link_to "Обратно ко всем постам", :back %>
  </div>

</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :stylesheets do %>
      <%= stylesheet_link_tag "zircon","jewelry", "comment" %>
    <% end %>

    <% content_for :javascripts do %>
      <%= javascript_include_tag "zircon" %>
    <% end %>
<section class="main-section">
      <% if @post.type == "IdeaPost" %>
        <%= render partial: "posts/postideapage", locals: {post: @post} %>
      <% end %>

        <% unless user_signed_in? %>
            <button class="bttn_save ">
               <img src="/assets/common/save.svg" alt="">
           </button>
        <% end %>
        <% if user_signed_in?%>
            <%= render "favorites/favorite", post: @post %>
        <% end %>


      <%#= render @post %>

        <div class="comment">
            <div class="comment__wrapper">

                <div class="title-group">
                    <h1 class="jewelry_title"><%= @post.comments.count %> комментария</h1>
                    <div class="divider__second">
                        <div class="highlight__second"></div>
                    </div>
                </div>
                <div class="comment">

                      <%#= render @post.comments, post: @post %>
                        <% @post.comments.each do |comment| %>
                            <%= render comment, post: @post %>
                        <% end %>

                    <div class="comment-form-container">
                        <%= render "comments/form", post: @post, comment: Comment.new %>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </dev>
</section>