config/routes.rb
Rails.application.routes.draw do

    get 'posts/search', to: 'posts#search'

    post 'support/request_support'

    resources :posts do
        collection do
            get "by_tag/:tag", to: "posts#by_tag", as: "tagged"
        end
    end

    resources :idea_posts do
        collection do
          get "by_tag/:tag", to: "idea_posts#by_tag", as: "tagged"
        end
    end

    resources :comments, only: [:create]

    namespace :api do
        namespace :v1 do
          resources :comments
          resources :posts

          devise_scope :user do
            post "sign_up", to: "registrations#create"
            post "sign_in", to: "sessions#create"
            post "sign_out", to: "sessions#destroy"
          end
        end
    end


    resources :posts, param: :slug do
        resource :favorite, only: [:create, :destroy]
    end

    devise_for :users

    get 'welcome/support'
    root "pages#trends"

    get 'search', to: 'pages#search'
    get 'stones', to: 'pages#stones'

    get 'history', to: 'pages#history'
    get 'jewelrystory', to: 'pages#jewelrystory'

    get 'cartier', to: 'pages#cartier'
    get 'trends', to: 'pages#trends'
    get 'zircon', to: 'pages#zircon'


    get 'lk', to: 'pages#lk'

     post 'support/request_support'

   resources :users
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::API
    # respond_to :json

    def decrypt_payload
        jwt = request.headers["Authorization"]
        payload = JWT.decode(jwt, Rails.application.credentials.devise_jwt_secret_key!, true, { algorithm: 'HS256' })
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    rescue_from CanCan::AccessDenied do |exception|
        respond_to do |format|
            format.json { head :forbidden }
            format.html { redirect_to root_path, notice: exception.message }
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer>
  <div class="container">
    <img class="footer__detail" src="#" alt="">
    <div class="subscribe__wrapper">
      <div class="row">
        <div class="follow">
          <h1 class="footer__name title--wht">
              <span class="footer_word"></span>Шкатулка
          </h1>
          <p class="footer__text">Шкатулка — самый утонченный медиа-сервис,<br>хранящий истории
            легендарных
            украшений<br>и драгоценных камней</p>
        </div>
        <div class="column">
          <div class="distribution__wrapper">
            <h3 class="distribution__title">Следите за нашими новостями!</h3>
            <div class="footer__flex">
              <div class="follow">
                <form action="" class="follow__form">
                  <input class="follow__email" type="email" placeholder="">
                  <button class="follow__btn" type="submit">Отправить</button>
                </form>
              </div>
            </div>
            <div class="wrapper__footer">
              <div class="wrapper__info">
                <div class="footer__info">
                  <h3 class="footer__subtitle">Поддержка</h3>
                  <ul class="footer__menu">
                    <li>
                      <%= link_to "Сообщить об ошибке", welcome_support_url, class: "footer__common text--opacity" %>
                    </li>
                    <li><a class="footer__common text--opacity" href="">shkatulka@mail.ru</a>
                    </li>
                  </ul>
                </div>
                <div class="footer__info">
                  <h3 class="footer__subtitle">О нас</h3>
                  <ul class="footer__menu">
                    <li><a class="footer__common text--opacity " href="">Команда</a></li>
                    <li><a class="footer__common text--opacity " href="">Правила
                      платформы</a>
                    </li>
                  </ul>
                </div>
              </div>
              <ul class="footer__detals">
                <li><a class="footer__common common--white ">Пользовательское
                  соглашение</a></li>
                <li><a class="footer__common common--white " href="">HSE ADC</a></li>
                <a class="copyright">@2023</a>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
</footer>

app/views/application/_menubar.html.erb
<header class="header">
 <div class="wrapper">
   <div class="header__logo search">
     <img class="logo" src="/assets/header/logo.svg" alt="">
     <h1 class="logo_title title title--black ">
       <span class="logo_word word">Ш</span>катулка
     </h1>
     <div class="header__icons icons">
         <% if user_signed_in?%>
                    <%= link_to "Выйти", destroy_user_session_path, method: :delete, class: "A_NavigationButton" %>
                <div class="header__icons icons">
                  <a href="/lk">
                    <img class="profile" src="/assets/header/profile.svg" alt="">
                  </a>
                </div>
         <% end %>
         <% unless user_signed_in? %>
            <%= link_to "Войти", new_user_session_path, class: "A_NavigationButton SignIn" %>
            <%= link_to "Регистрация", new_user_registration_path, class: "A_NavigationButton"  %>
         <% end %>
       <a href="<%= search_path %>">
         <img class="Search" src="/assets/header/Search.svg" alt="">
       </a>
     </div>
   </div>
   <div class="divider">
     <div class="highlight"></div>
   </div>
   <div class="header__nav nav">
        <a class="nav__link<%=  current_page?(root_path) || current_page?(trends_path) ? ' nav__link--selected' : '' %>" href="<%= trends_path %>">Тренды</a>
        <a class="nav__link<%= current_page?(stones_path) ? ' nav__link--selected' : '' %>" href="<%= stones_path %>">Камни</a>
        <a class="nav__link<%= current_page?(jewelrystory_path) ? ' nav__link--selected' : '' %>" href="<%= jewelrystory_path %>">Украшения</a>
        <a class="nav__link<%= current_page?(history_path) ? ' nav__link--selected' : '' %>" href="<%= history_path %>">История</a>
   </div>
 </div>
</header>